language: php
# notifications:
#   email: false

php:
  - '7.4'
  - '7.2'
# env:
#   - WP_TRAVISCI=travis:phpunit
before_script: echo "Before script call"
before_install: echo "Before install call"
script: echo "Script call" 
install: echo "install call"