sudo: required
language: php

php:
  - '7.4'

matrix:
  fast_finish: true
  # allow_failures:
  #   - php: 7.4
  #   - env: WP_VERSION=5.6

services:
  - mysql

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache/files


