language: php
# notifications:
#   email: false

php:
  - '7.4'
  - '7.2'

services:
  - postgresql
# env:
#   - WP_TRAVISCI=travis:phpunit
#before_script: 
#  - echo "Before script call"
#  - chmod +x build.sh
#  - ./build.sh
before_install: echo "Before install call"

install: echo "install call"
script: 
  - echo "Script call" 
  - chmod +x build-1.sh
  - ./build-1.sh
