language: php
notifications:
  email: false

php:
  - '7.4'
env:
  - WP_TRAVISCI=travis:phpunit
before_install:
  - chmod +x build.sh
jobs:
  fast_finish: true
  include:
    - stage: "Test stage 1"
      if: type != pull_request
    - script: "Running stage Test stage"
    - script: ./build.sh
    - stage: "Test Stage 2"
      if: type = pull_request
      script: ./build.sh
    - stage: "Test Stage 3"
      script: "Running test stage 3"
      script: ./build.sh
script: skip 