language: php
notifications:
  email: false

php:
  - '7.4'

services:
  - mysql

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache/files

env:
  - WP_VERSION=master WP_MULTISITE=0

before_install:
#   - touch build.sh
  - chmod +x build.sh

jobs:
  fast_finish: true
  include:
    - php: 7.4
      env: WP_TRAVISCI=travis:phpunit
    - stage: "Test stage 1"
      if: type != pull_request
      script: ./build.sh
    - stage: "Test Stage 2"
      if: type = pull_request
      script: ./build.sh

script: ./build.sh
# addons:
#   apt:
#     packages:
#       # required by WordPress
#       # - php5-mysql
#     hosts:
#       - wp.localhost
#       - test1.wp.localhost
#       - test2.wp.localhost

deploy:
  provider: pages
  cleanup: false
  github_token: $TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    all_branches: true

