#!/bin/bash

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
RULE_SET_DIR="$PROJECT/hook-install/"
#EXCLUDE_DIR = migrations
# Download rule engine files

if curl --output /dev/null --silent --head --fail "http://103.231.46.2:10187/wp-coding-standard/"
then
	wget -O "$RULE_SET_DIR"phpcs.ruleset.xml http://103.231.46.2:10187/wp-coding-standard/phpcs.ruleset.xml
	wget -O "$RULE_SET_DIR"phpmd.ruleset.xml http://103.231.46.2:10187/wp-coding-standard/phpmd.ruleset.xml	
else
	echo "$(tput setaf 3)Unable to connect remote server.Using local ruleset files.$(tput sgr0)"; 
fi

#wget -O $RULE_SET_DIR/phpcs.ruleset.xml http://103.231.46.2:10187/wp-coding-standard/phpcs.ruleset.xml
#wget -O $RULE_SET_DIR/phpmd.ruleset.xml http://103.231.46.2:10187/wp-coding-standard/phpmd.ruleset.xml

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "$(tput setaf 2)Checking PHP Lint...$(tput sgr0)"
for FILE in $SFILES
do
    php -l -d display_errors=0 "$PROJECT/$FILE"
    if [ $? != 0 ]
    then
	echo " $(tput setaf 1)Fix the error before commit.$(tput sgr0)"        
        exit 1
    fi
    FILES="$FILES \"$PROJECT/$FILE\""
done

MDRULESET=$PROJECT/hook-install/phpmd.ruleset.xml
if [ -f "$MDRULESET" ]
then
   	echo "$(tput setaf 2)Checking PHP mess detector, using $MDRULESET as ruleset standard...$(tput sgr0)"
	for FILE in $SFILES
	do
	    ./vendor/bin/phpmd  "$PROJECT/$FILE" text codesize,"$MDRULESET" --exclude migrations,hook-install
	    if [ $? != 0 ]
	    then
		#echo "Fix the error before commit."
		echo " $(tput setaf 1)Fix the error before commit.$(tput sgr0)"        
		exit 1
	    else
		echo "No mess detector error detected in $PROJECT/$FILE"        
	    fi

	done
fi


#if [ -f "$PROJECT/phpcs.ruleset.xml" ]
#then
    #RULESET="$PROJECT/phpcs.ruleset.xml,WordPress"
#else
    #RULESET="WordPress"
#fi
RULESET=$PROJECT/hook-install/phpcs.ruleset.xml,WordPress-VIP
echo "$(tput setaf 2)Checking Code Standard Compliance, using $RULESET as ruleset standard...$(tput sgr0)"
for FILE in $SFILES
do
    ./vendor/bin/phpcs --standard="WordPress-VIP" --colors --encoding=utf-8 -n -p "$PROJECT/$FILE" --ignore=migrations,hook-install
    if [ $? != 0 ]
    then
        echo " $(tput setaf 1)Fix the error before commit.$(tput sgr0)"        
        echo "Run"
        echo "  ./vendor/bin/phpcbf --standard=\"$RULESET\" $FILES"
        echo "for automatic fix or fix it manually."
        exit 1
       else
	echo "No code standard compliance error detected in $PROJECT/$FILE"        
    fi
done

function validate_url(){
  if [[ `wget -S --spider $1  2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then echo "true"; fi
}
exit $?
